n_runs: 40
examples_count: 10
print_only: true
clean_first: true

include_case_attributes: true
include_log_info: true

included_inter_case:
  - timesincemidnight
  - weekday
  - month
  - timesincelastevent
  # - timesincecasestart
  - event_nr
  - prev_resource
  - ent_act
  - ent_case
  - ent_handoff
  - busyness
  #- open_cases
  - res_work_items
  - res_cases
  - res_unique_tasks
  - res_unique_handoffs
  - res_ratio_workitems_global
  - res_ratio_workitems_resource
  - res_ratio_task_specific
  - res_ratio_handoff_specific
  - res_work_items_per_min
  # - act_freq
  # - handoff_freq
