log_name: bpic2020_international_declarations
log_description: The dataset contains events pertaining to two years of travel expense claims from international declarations.
columns:
  case_id: Case ID
  activity: Activity
  resource: Resource
  timestamp: Complete Timestamp
case_attributes:
  Amount: the declared amount
