log_name: bpic2020_request_for_payment
log_description: The dataset contains events pertaining to two years of travel expense claims.
columns:
  case_id: Case ID
  activity: Activity
  resource: Resource
  timestamp: Complete Timestamp
case_attributes:
  RequestedAmount: the requested amount
