log_name: bpic2012
log_description: The considered process deals with the loan application process from a Dutch financial institution. It has been provided in the Business Process Intelligence (BPI) challenge in 2012.
columns:
  case_id: case
  activity: event
  resource: org:resource
  timestamp: completeTime
case_attributes:
  AMOUNT_REQ: the requested loan amount
